export const SIGN_IN_SUCCCESS = 'SIGN_IN_SUCCCESS';
export const SIGN_OUT_SUCCCESS = 'SIGN_OUT_SUCCCESS';

export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAIL = 'FETCH_USER_FAIL';